---
# tasks file for ssh

- name: Ensure issue.net file is configured
  become: yes
  copy:
    src=issue.net
    dest=/etc/issue.net
    backup=yes
    owner=0
    group=0
    mode=0644
  tags: ssh
  notify: Restart SSH server

- name: Ensure SSH server is configured
  become: yes
  template:
    src=sshd/sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0
    group=0
    mode=0644
    validate='/usr/sbin/sshd -T -f %s'
  tags: ssh
  notify: Restart SSH server
